blank_issues_enabled: false
contact_links:
  - name: BusinessElite+ Discord
    url: https://discord.com/invite/57YkapsHJW
    about: For assistance in making issues, or if you have questions/concerns please join the Discord
